fix: use utf-8 encoding for csv reading
jina-ai/docarray pull request #112
Opened 2022-02-13 15:40 UTC by jacobowitz

I am not 100% sure about this PR, so please think about it **carefully**.

In Jina the chatbot example is currently broken in Windows, because the csv dataset cant be read correctly. This file [here]('https://static.jina.ai/chatbot/dataset.csv') .

Reading this file with `DocumentArray.from_csv` will result in this error:

`
File "c:\users\tobias\pycharmprojects\hello_jina\venv\lib\site-packages\docarray\document\generators.py", line 302, in _sample
    for i in iterable:
  File "C:\Users\tobias\AppData\Local\Programs\Python\Python38\lib\csv.py", line 111, in next
    row = next(self.reader)
  File "C:\Users\tobias\AppData\Local\Programs\Python\Python38\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 3204: character maps to <undefined>
`

The problem is that the csv file is opened without providing any encoding. This means [Python will use some OS dependant encoding](https://docs.python.org/3/library/functions.html#open). Linux correctly assumes 'utf-8', but Windows tries `cp1252` and fails.

Thus this PR hard codes the encoding to `utf-8`, which should work in most cases I think. I am not sure about some undesired side effects in some Operating systems though.

2022-02-13 19:28 UTC, JoanFM reviewed
Maybe we can simply add `encoding` as an option with `utf-8` as default

2022-02-14 07:55 UTC, numb3r3 requested changes

2022-02-14 07:55 UTC, numb3r3 commented on docarray/document/generators.py
> +        file_ctx = open(file, 'r', encoding='utf-8')
And the writing function `save_embeddings_csv` has the save issue.

2022-02-14 08:27 UTC, samsja commented
FYI: that's how pandas deal with it : https://github.com/pandas-dev/pandas/blob/b365376044c28f8f0a6767c1657bd62327d7ae09/pandas/io/parsers/readers.py#L1054
I am not sure what the  `sys.getfilesystemencoding()` is returning on windows

2022-02-14 08:36 UTC, JoanFM commented
> FYI: that's how pandas deal with it : https://github.com/pandas-dev/pandas/blob/b365376044c28f8f0a6767c1657bd62327d7ae09/pandas/io/parsers/readers.py#L1054 I am not sure what the `sys.getfilesystemencoding()` is returning on windows

This would make sense, lets implement this

2022-02-14 08:41 UTC, numb3r3 commented
> This would make sense, lets implement this

I would not implement like this way. To make sure the encoding of the dumped files is **system independently**, I recommend using `UTF-8` as the default without special reason.

2022-02-14 11:23 UTC, numb3r3 approved these changes

2022-02-14 11:24 UTC, JoanFM approved these changes

2022-02-14 11:24 UTC, merged