docs: construct nested document line by line
jina-ai/docarray pull request #20
Opened 2022-01-10 16:40 UTC by bwanglzu

create nested documents with one-liner could break the `granularity`, the recommended way: 
![61FF2853-73B9-4351-882E-114619A58AE5](https://user-images.githubusercontent.com/9794489/148803456-ff118c01-1abc-4a4f-b760-bc30fff9c8dd.png)

2022-01-10 19:29 UTC, hanxiao commented
i dont see why original code does not work

2022-01-10 19:33 UTC, JoanFM commented
> i dont see why original code does not work

Because chunks are constructed before being added to the list.

2022-01-10 19:36 UTC, JoanFM commented
> > i dont see why original code does not work
> 
> Because chunks are constructed before being added to the list.

So a Document A is created standalone (therefore granularity 0) and then by creating a Document B with A as chunk, B does not update A's granularity.

2022-01-10 19:56 UTC, hanxiao commented
can you show the code and result because i believe i solved it

2022-01-12 05:28 UTC, nan-wang commented
@hanxiao Here is the codes to show the issue

```python
from docarray import Document
d = Document(
    id='d0',
    chunks=[Document(id='d1', chunks=Document(id='d2'))],
    matches=[Document(id='d3', matches=Document(id='d4'))],
)

for c in d.chunks:
    print(f'{c.id}: g={c.granularity}')
    for cc in c.chunks:
        print(f'{cc.id}: g={cc.granularity}')

for m in d.matches:
    print(f'{m.id}: g={m.granularity}, a={m.adjacency}')
    for mm in m.matches:
        print(f'{mm.id}: g={mm.granularity}, a={mm.adjacency}')
```

The outputs is as below where 
- `d2` is expected to have `granularity=2`
- `d4` is expected to have `adjacency=2`

```diff
d1: g=1
d2: g=1
d3: g=0, a=1
d4: g=0, a=1
```

2022-01-12 05:33 UTC, nan-wang requested changes

2022-01-12 05:33 UTC, nan-wang commented on docs/fundamentals/document/construct.md
> +d.matches.append(Document(id='d3'))
We can further show the adjacency as well
```suggestion
d.matches.append(Document(id='d3'))
d.matches[0].matches.append(Document(id='d4'))
```

2022-01-12 10:58 UTC, bwanglzu commented
as was discussed , it works at `g=1`, not `g>1`, such as 2

2022-01-12 13:51 UTC, nan-wang approved these changes
LGTM👍

2022-01-12 15:14 UTC, hanxiao commented
reject. it overreact. single nested works so don't rewrite all just because double nested don't work

2022-01-12 15:15 UTC, hanxiao requested changes
reject as it overreacts

2022-01-12 15:21 UTC, bwanglzu commented
close the PR since not necessary.

2022-01-12 15:21 UTC, closed without merging