feat: plot matching sprite funs
jina-ai/docarray pull request #265
Opened 2022-04-07 12:00 UTC by makram93

This PR adds functionality to show matching images in a sprite. The leftmost is the query followed by matching results. There is a gap between the query and its matches to distinguish/differentiate.
![image](https://user-images.githubusercontent.com/6537525/162193668-64e14f94-c0b1-4eef-a372-dcbd8d663448.png)

2022-04-07 15:05 UTC, bwanglzu reviewed
left some comments

2022-04-07 15:05 UTC, bwanglzu commented on docarray/document/mixins/plot.py
> +            raise ValueError(f'image_source can be only `uri` or `tensor`')
with the literal check, this is not needed anymore

2022-04-07 15:05 UTC, bwanglzu commented on docarray/document/mixins/plot.py
> +            channel_axis = -1
maybe you need `load_uri_to_image_tensor(channel_axis=channel_axis)`? then why do you need `channel_axis` as an argument pass into this function?

2022-04-07 15:39 UTC, makram93 commented on docarray/document/mixins/plot.py
> +        image_source: str = 'tensor',
Thanks for the pointer :)

2022-04-07 16:16 UTC, bwanglzu commented
@makram93 mybad, `literal` only works on py3.8+, please ignore my first 2 comments.

2022-04-07 19:53 UTC, hanxiao commented on docarray/document/mixins/plot.py
> +    def plot_matching_sprites(
```suggestion
    def plot_matches_sprites(
```

2022-04-08 12:59 UTC, bwanglzu approved these changes
LGTM!

2022-04-08 15:52 UTC, hanxiao requested changes
need a doc, subsection under this https://docarray.jina.ai/fundamentals/documentarray/visualization/#image-sprites

2022-04-11 07:41 UTC, hanxiao approved these changes

2022-04-11 09:38 UTC, merged