test(image): add unit tests for _to_image_tensor
jina-ai/docarray pull request #281
Opened 2022-04-17 16:01 UTC by alessiamarcolini

This PR is adding two unit tests for the function `_to_image_tensor` in `docarray/document/mixins/image.py`.

--- 
**Note**: I could not find a way to cover lines 340-341: https://github.com/jina-ai/docarray/blob/73f2aef9d3145f4d29982681fc8632230c37fdf4/docarray/document/mixins/image.py#L338-L341

By looking at the internals of `PIL.Image.convert`, it seems like there is no way to read the image correctly at
https://github.com/jina-ai/docarray/blob/73f2aef9d3145f4d29982681fc8632230c37fdf4/docarray/document/mixins/image.py#L333

and then make it fail during the conversion to `RGB`. Could it be a leftover/patch for something weird that happened in the past? If not, how can this be meaningfully tested?

2022-04-19 08:15 UTC, alaeddine-13 commented
Hey @alessiamarcolini , thanks for your contribution.
I don't think that private functions should be tested. Instead, we can try to cover those cases in public methods that use it.
For example, you can try covering the cases of width and height != None to `convert_blob_to_image_tensor` which should cover more lines in _to_image_tensor

2022-04-19 08:53 UTC, alessiamarcolini commented
Hi @alaeddine-13, thank you for your comment.
Is testing only public methods/functions part of the project guidelines? If so, I think it should be mentioned in the [CONTRIBUTING.md](https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md) to inform future contributors.

Should I remove the tests then and write new ones for `convert_blob_to_image_tensor`? Or can I keep the existing ones?
Thank you.

2022-04-19 15:53 UTC, hanxiao requested changes
thanks for the PR. @alaeddine-13 she does improve the coverage, so I think it's good

one remark, we use single quote for string in the codebase. So please adjust accordingly

2022-04-20 00:02 UTC, alaeddine-13 commented on tests/unit/document/test_image.py
> +    RGB_COLOR_10X50_155_0_0.save(img_path)
```suggestion
    image = Image.new('RGB', size=(10, 50), color=(0, 0, 0))
    image.save(img_path)
```

2022-04-20 00:33 UTC, alaeddine-13 approved these changes

2022-04-20 00:34 UTC, alaeddine-13 commented
Thanks @alessiamarcolini for your contribution!

2022-04-20 00:34 UTC, merged