feat: load jina auth token from environment
jina-ai/docarray pull request #368
Opened 2022-05-24 14:43 UTC by gmastrapas

Goals:

- Enable passing Jina authentication token from the environment for `da.push` and `DocumentArray.pull`. Uses key `JINA_AUTH_TOKEN`
- [ ] check and update documentation, if required. See [guide](https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md#documentation-guidelines)

2022-05-25 12:16 UTC, JoanFM requested changes

2022-05-25 12:21 UTC, gmastrapas commented on tests/unit/array/mixins/test_pushpull.py
> +    os.environ['JINA_AUTH_TOKEN'] = token
I unset the env var in the same tests

2022-05-25 12:24 UTC, JoanFM commented on tests/unit/array/mixins/test_pushpull.py
> +    os.environ['JINA_AUTH_TOKEN'] = token
yes, but what if there is an Exception in the middle, then this part of the code is not executed

2022-05-25 12:51 UTC, gmastrapas commented on tests/unit/array/mixins/test_pushpull.py
> +    os.environ['JINA_AUTH_TOKEN'] = token
ok makes sense

2022-05-27 13:37 UTC, alaeddine-13 commented on tests/unit/array/mixins/test_pushpull.py
> +    assert pull_kwargs['headers'].get('Authorization') == f'token test-auth-token'
```suggestion
    assert push_kwargs['headers'].get('Authorization') == 'token test-auth-token'
    assert pull_kwargs['headers'].get('Authorization') == 'token test-auth-token'
```

2022-05-27 13:37 UTC, alaeddine-13 commented on docarray/array/mixins/io/pushpull.py
> +    return _env_auth_token or _config_auth_token
```suggestion
    hub_config = _get_hub_config()
    config_auth_token = hub_config.get('auth_token') if hub_config else None
    env_auth_token = os.environ.get('JINA_AUTH_TOKEN')
    return env_auth_token or config_auth_token
```

2022-05-27 13:37 UTC, alaeddine-13 commented on tests/unit/array/mixins/test_pushpull.py
> +def test_api_authorization_header_from_env(mocker, monkeypatch, set_env_vars):
let's just add one last test that asserts the priority in case both are set

2022-05-28 07:44 UTC, JoanFM approved these changes

2022-05-30 07:42 UTC, alaeddine-13 approved these changes

2022-05-30 07:43 UTC, merged