feat: bump protobuf
jina-ai/docarray pull request #371
Opened 2022-05-26 09:15 UTC by JoanFM

Goals:

- ...
- ...
- [ ] check and update documentation, if required. See [guide](https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md#documentation-guidelines)

2022-08-21 21:34 UTC, hanxiao commented
@alaeddine-13 please take care of this PR thanks, we have to move forward. It doesn't make sense to be blocked by paddle because of the lack of maintenance on their side. Refactor the tests or in the worst case, remove paddle tests (or even functions). Move this PR forward at any cost.

2022-08-22 15:03 UTC, alaeddine-13 commented
we're proceeding like so:

1. create another protoc gen image with new version
2. build protos in 2 versions (old and new)
3. in docarray and jina, dynamically find the version of protobuf and accordingly, use the appropriate protobuf file

2022-08-23 19:59 UTC, hanxiao commented on docarray/proto/__init__.py
> +if __pb__version__.startswith('4'):
aha, smart

2022-08-23 19:59 UTC, hanxiao approved these changes

2022-08-23 20:03 UTC, hanxiao requested changes
could you also change `__version__ = 0.16.0` so 

after this merge,
1. the corresponding PR in core has to be merged, with version restriction of `docarray >=0.16.0` and its own `__version=3.18.0`
2. docarray release `0.16.0`
3. jina release `3.8.0`

2022-08-24 10:40 UTC, alaeddine-13 commented
> 



> could you also change `__version__ = 0.16.0` so
> 
> after this merge,
> 
> 1. the corresponding PR in core has to be merged, with version restriction of `docarray >=0.16.0` and its own `__version=3.18.0`
> 2. docarray release `0.16.0`
> 3. jina release `3.8.0`

I agree on this
old jina versions will no more be compatible with new docarray and installing old versions of jina becomes buggy
the dependency here should be fixed to use docarray~=0.16.0: https://github.com/jina-ai/jina/blob/master/extra-requirements.txt#L35

2022-08-26 15:36 UTC, hanxiao commented
i haven't looked at the protobuf docs generation, is it affected?

2022-08-26 16:01 UTC, merged