feat: filter in weav
jina-ai/docarray pull request #373
Opened 2022-05-26 15:07 UTC by davidbp

2022-06-01 12:47 UTC, JoanFM requested changes

2022-06-02 07:37 UTC, alaeddine-13 commented on docs/advanced/document-store/weaviate.md
> +Then you can retrieve all documents whose price is lower or equal than `max_price` applying the following
```suggestion
Then you can retrieve all documents whose price is lower than or equal to `max_price` by applying the following 
```

2022-06-02 07:37 UTC, alaeddine-13 commented on docs/advanced/document-store/weaviate.md
> + Returned examples that verify filter "price at most 3":
```suggestion
 Returned examples that satisfy condition "price at most 3":
```

2022-06-02 07:37 UTC, alaeddine-13 commented on docs/advanced/document-store/weaviate.md
> +### Example of `.find` with  query vector and filter
```suggestion
### Example of `.find` with query vector and filter
```

2022-06-02 07:39 UTC, alaeddine-13 commented on docs/advanced/document-store/weaviate.md
> +### Example of `.find` with only a  filter
```suggestion
### Example of `.find` with a  filter only
```

2022-06-02 07:52 UTC, davidbp commented on docs/advanced/document-store/weaviate.md
> +                              })
yes, done

2022-06-02 10:00 UTC, JoanFM approved these changes

2022-06-02 10:06 UTC, merged