fix(elastic): inconsistent offset on bulk index error and improve bulk performance
jina-ai/docarray pull request #422
Opened 2022-06-29 10:23 UTC by alphinside

Goals:

On bulk index submit, if there is error occured ( for example if data type provided is wrong ( in test, I give example by providing int64 data inserted into int32 column )), it will raise BulkIndexError, however the documents is still inserted to the main index but due to error raises, the offset is not updated.

In this PR, I try to fix the issue and also increase the performance by using parallel_bulk and set raise_on_error to False, then return the index error info to the caller

- ...
- ...
- [x] check and update documentation, if required. See [guide](https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md#documentation-guidelines)

2022-06-29 10:41 UTC, JoanFM requested changes
Are we sure this `not raise on error behavior` is compatible with the rest of the backends?

2022-06-29 10:41 UTC, JoanFM commented on docarray/array/storage/elastic/backend.py
> +            if success is not True:
```suggestion
            if not success:
```

2022-06-29 10:48 UTC, alphinside commented on docarray/array/storage/elastic/seqlike.py
> +        failed_ids = [index['_id'] for index in failed_index]
yes, thats also what I thought, any reference of logger that you guys use, or just use the standard `logging` one?

2022-06-29 11:17 UTC, hanxiao commented on docarray/array/storage/elastic/seqlike.py
> +        failed_ids = [index['_id'] for index in failed_index]
This is a very customized behavior. I wouldn't recommend. To me this is basically play a ding sound on every success insert, which does not make it feel like Python List container.

Notice that the design principle of DocArray package and DocumentArray is making it a List-Like object.

This customized behavior violates this design principle.

2022-06-29 11:18 UTC, hanxiao requested changes
https://github.com/jina-ai/docarray/pull/422#discussion_r909507152

2022-06-29 11:24 UTC, alphinside commented on docarray/array/storage/elastic/seqlike.py
> +        failed_ids = [index['_id'] for index in failed_index]
will be waiting @JoanFM decision on this, whether we treat extend operation as atomic or not

2022-06-30 09:43 UTC, JoanFM requested changes
I have been reading the code, and what seems more coherent with rest of backends would be to `raise` an Exception (without reverting the proper appends) and informing via warning what `Docs` were not able to be appended.

It seems to me that is the more `SeqLike` behavior there is. What do you think @alphinside ?

2022-06-30 22:06 UTC, alphinside commented
> I have been reading the code, and what seems more coherent with rest of backends would be to `raise` an Exception (without reverting the proper appends) and informing via warning what `Docs` were not able to be appended.
> 
> It seems to me that is the more `SeqLike` behavior there is. What do you think @alphinside ?

yes , I agree will update on that aspect

2022-07-01 10:02 UTC, JoanFM approved these changes
LGTM!

2022-07-01 10:04 UTC, merged