feat(redis): add logic operators $and and $or in redis
jina-ai/docarray pull request #509
Opened 2022-08-30 05:15 UTC by AnneYang720

This PR will support logic operators $and and $or in redis according to https://github.com/jina-ai/docarray/issues/501

2022-09-02 15:48 UTC, bwanglzu requested changes
some minor comments, please always use single quote.

2022-09-02 15:48 UTC, bwanglzu commented on docarray/array/storage/redis/find.py
> +            query_str = "*"
```suggestion
            query_str = '*'
```

2022-09-02 15:48 UTC, bwanglzu commented on docarray/array/storage/redis/find.py
> +            if isinstance(value, (bool)):
what is `(bool)`?

2022-09-02 15:48 UTC, bwanglzu commented on docarray/array/storage/redis/find.py
> +        if k == "$and":
single quote

2022-09-02 15:48 UTC, bwanglzu commented on tests/unit/array/mixins/test_find.py
> +    )
your `filters1` to `filters4` can be parameters and your expected output can be parameters to simplify your test

2022-09-05 08:12 UTC, bwanglzu requested changes
minor comments

2022-09-05 08:12 UTC, bwanglzu commented on docarray/array/storage/redis/find.py
> +    return node
i modified it a bit for simplicity:

```python

def _build_query_node(key, condition):
    operator = list(condition.keys())[0]
    value = condition[operator]

    query_dict = {}

    if operator in ['$ne', 'eq']:
        if isinstance(value, bool):
            query_dict[key] = equal(int(value))
        elif isinstance(value, (int, float)):
            query_dict[key] = equal(value)
        else:
            query_dict[key] = value
    elif operator == '$gt':
        query_dict[key] = gt(value)
    elif operator == '$gte':
        query_dict[key] = ge(value)
    elif operator == '$lt':
        query_dict[key] = lt(value)
    elif operator == '$lte':
        query_dict[key] = le(value)
    else:
        raise ...

    if operator == '$ne':
        return DistjunctUnion(**query_dict)
    return IntersectNode(**query_dict)
```

2022-09-06 09:08 UTC, bwanglzu approved these changes
LGTM!

2022-09-06 09:11 UTC, JoanFM requested changes
Wait for merging PR where column types is set to Dict

2022-09-07 08:04 UTC, AnneYang720 commented on docs/advanced/document-store/redis.md
> +```JSON
okay

2022-09-08 16:34 UTC, alaeddine-13 approved these changes
LGTM, well done !

2022-09-08 17:54 UTC, JoanFM approved these changes

2022-09-08 17:55 UTC, merged