fix: correctly allow to load from a databased setup with subindices
jina-ai/docarray pull request #554
Opened 2022-09-22 14:32 UTC by samsja

# context 

ATM we could not read from a database which has been setup with sub indices. This pr fix this (original issue [here](https://github.com/jina-ai/docarray/issues/555) ) 

```python

from docarray import Document, DocumentArray, dataclass
from docarray.typing import Image, Text

@dataclass
class MyDocument:
    image: Image
    paragraph: Text

# extend with Documents, including embeddings
_docs = [(MyDocument( image='https://docarray.jina.ai/_images/apple.png', paragraph='hello world'))]

da = DocumentArray(
    storage='sqlite',  # use SQLite as vector database
    config={'connection': 'jina4.db', 'table_name': 'test4'},
    subindex_configs={'@.[image]': {'connection': 'jina4.db', 'table_name': 'test5'}, '@.[paragraph]': {'connection': 'jina4.db', 'table_name': 'test6'}},  # set up subindices for image and description
)
da.summary()

for item in _docs:
  d = Document(item)
  da.append(d)

da = DocumentArray(
    storage='sqlite',  # use SQLite as vector database
    config={'connection': 'jina4.db', 'table_name': 'test4'},
    subindex_configs={'@.[image]': {'connection': 'jina4.db', 'table_name': 'test5'}, '@.[paragraph]': {'connection': 'jina4.db', 'table_name': 'test6'}},  # set up subindices for image and description
)
da.summary()
```

This will now work

2022-09-22 14:36 UTC, alaeddine-13 approved these changes

2022-09-22 14:48 UTC, alaeddine-13 reviewed
can we have a test that shows the error ?
ideally across all backends

2022-09-22 15:01 UTC, JoanFM requested changes
Can we please add a test?

2022-09-26 08:11 UTC, alaeddine-13 reviewed
~~let's add a test that should fail before adding the fix~~
ignore my comment I thought I didn't review

2022-09-28 11:14 UTC, alaeddine-13 approved these changes

2022-09-29 03:47 UTC, dongxiang123 commented
All tests are passed, and we can close this ticket.

2022-09-29 07:29 UTC, samsja reviewed
should we include a test ?

2022-09-30 07:11 UTC, JoanFM requested changes

2022-09-30 07:11 UTC, JoanFM commented on tests/unit/document/test_database_subindices.py
> +    _docs = [(MyDocument( image='https://docarray.jina.ai/_images/apple.png', paragraph='hello world'))]
make sure to add a local dependency, this test may fail in case some documentation change happens in the repo, or docarray website is down ...

2022-09-30 07:11 UTC, JoanFM commented on tests/unit/document/test_database_subindices.py
> +        config={'connection': 'jina4.db', 'table_name': 'test4'},
can u keep the `config` as a variable so that is easily seen that they are the same

2022-09-30 07:15 UTC, JoanFM commented
@samsja , @dongxiang123  let's close this PR and have @dongxiang123 open a new one

2022-09-30 07:31 UTC, closed without merging