docs: explain better docstring of set_image_normalization
jina-ai/docarray pull request #585
Opened 2022-10-03 14:24 UTC by JoanFM

Goals:
Fix problems described in #513 , clarify in docstring proper usage of `set_image_normalization` with respect to the axis and the shapes of the tensors

2022-10-03 16:55 UTC, alaeddine-13 commented on docarray/document/mixins/image.py
> +        Following Pytorch standard, the image will be reshaped to (3 x H x W) and
```suggestion
        Following Pytorch standard, the image will be reshaped to (3 x H x W),
```

2022-10-04 07:11 UTC, JohannesMessner requested changes

2022-10-04 07:47 UTC, JoanFM commented on docarray/document/mixins/image.py
> +        normalized using mean = [0.485, 0.456, 0.406] and std = [0.229, 0.224, 0.225]. After normalization, the image will be transformed back into the original shape.
Original shape, it is important that the `mean, std` come with 3xHxW in mind.

2022-10-04 08:07 UTC, JohannesMessner commented on docarray/document/mixins/image.py
>          will be normalized in to a range of [0, 1] and then
```suggestion
```

2022-10-04 08:54 UTC, JohannesMessner approved these changes

2022-10-04 09:47 UTC, merged