feat(qdrant): pass search_params in find
jina-ai/docarray pull request #675
Opened 2022-10-25 08:24 UTC by AnneYang720

Goals:
This PR is related to issue #666  
Change PR #668 to jina branch.

 - [ ] update code
 - [ ] add test
 - [ ] update documentation

2022-10-25 08:33 UTC, JoanFM requested changes

2022-10-25 08:33 UTC, JoanFM commented on docarray/array/storage/qdrant/find.py
> +        search_params: Optional[Dict] = {},
please set `None` as default and handle properly

2022-10-25 08:40 UTC, JoanFM requested changes

2022-10-25 08:40 UTC, JoanFM commented on tests/unit/array/storage/qdrant/test_find.py
> +        if kwargs['search_params']:
this test would pass, even if the feature did not work

2022-10-25 08:50 UTC, JoanFM approved these changes

2022-10-25 08:51 UTC, JoanFM requested changes

2022-10-25 08:51 UTC, JoanFM commented on tests/unit/array/storage/qdrant/test_find.py
> +def test_success_find_with_added_kwargs(start_storage, monkeypatch):
You can parametrize the test with `search` params and expected, so u can test both cases

2022-10-25 11:36 UTC, JoanFM approved these changes

2022-10-25 13:22 UTC, JoanFM requested changes
Wait until @NicholasDunham approval

2022-10-26 02:18 UTC, NicholasDunham approved these changes

2022-10-26 06:41 UTC, JoanFM approved these changes

2022-10-26 06:54 UTC, merged