chore: remove join jina ai
jina-ai/docarray pull request #692
Opened 2022-10-25 15:11 UTC by samsja

# Context

This pr remove the links the Jina AI

2022-10-25 16:29 UTC, NicholasDunham approved these changes

2022-10-25 16:57 UTC, JoanFM requested changes
Let's wait until LFAI acceptance.

2022-10-26 07:26 UTC, samsja commented on docs/get-started/what-is.md
> +DocArray focuses on local and monolith developer experience. Jina scales DocArray to the Cloud.
yeah my bad

2022-11-02 11:31 UTC, hanxiao commented on docs/index.md
>  fundamentals/notebook-support/index
keep this

2022-11-02 11:31 UTC, hanxiao commented on docs/index.md
>  fundamentals/notebook-support/index
```suggestion
fundamentals/jina-support/index
fundamentals/notebook-support/index
```

2022-11-02 11:33 UTC, hanxiao requested changes
~~Keep "Jina support" section~~
actually, never mind

2022-11-02 12:48 UTC, JoanFM approved these changes

2022-11-02 12:49 UTC, merged