feat: add first implemenation of embed_and_evaluate
jina-ai/docarray pull request #702
Opened 2022-10-28 09:53 UTC by guenthermi

Goals:

- add a function that does embed, match, and evaluate at once
- do embed and match in batches to reduce the memory foot-print of the method
- [ ] check and update documentation, if required. See [guide](https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md#documentation-guidelines)

2022-10-28 09:54 UTC, guenthermi commented
This is only a draft atm. I have to add more tests, benchmark the memory usage, add add documentation if everything seems to work well.

2022-10-31 13:21 UTC, samsja requested changes
lgtm, could we change the docstring of `embed` to mention that this new method exist and should be used when the user need to do embed and eval directly ?

2022-10-31 13:32 UTC, guenthermi commented on docarray/array/mixins/evaluation.py
> +            if not label_tag in index_data[0].tags:
Yes, but I don't think it is necessary to do a full data validation. If a user provides only partly labels, I think it is ok if it crashes with a key error.

2022-10-31 13:45 UTC, samsja commented on docarray/array/mixins/evaluation.py
> +        :param index_data: The other DocumentArray  to match against, if not given,
match everything against everything is not tracktable tbh, why not just do the sampling right now ?

2022-10-31 14:15 UTC, guenthermi commented on docarray/array/mixins/evaluation.py
> +        :param index_data: The other DocumentArray  to match against, if not given,
Note: We discussed that it might make sense, but it is better to implement it in this PR to avoid a breaking change.

2022-11-01 07:56 UTC, samsja commented on docarray/array/mixins/evaluation.py
> +            if not label_tag in index_data[0].tags:
@JohannesMessner @alaeddine-13 what is your opinion here ? For me it is either we do it for every doc on we don't do validation but I might be wrong

2022-11-02 11:48 UTC, hanxiao approved these changes

2022-11-02 11:49 UTC, merged