feat: add 3d data handling of mesh vertices and faces
jina-ai/docarray pull request #709
Opened 2022-10-31 11:01 UTC by anna-charlotte

Goals:

- Currently, DocArray only supports point clouds for 3d data representation. 
- We want to add functions to additionally support 3d data representation of meshes, which include more information about a 3d object than a point cloud, and seem to be more commonly used. Meshes basically consist of a vertices tensor and a faces tensor, which I plan to load to load to chunks, i.e.:

```python
from docarray import Document

doc = Document(uri='some/uri')
doc.load_uri_to_vertices_and_faces_tensors()

# resulting in:
# doc = Document(
#     uri='some/uri', 
#     chunks=[
#         Document(name='vertices', tensor=sometensor), 
#         Document(name='faces', tensor=sometensor)
#     ]
# )
```

- [x] add `load_uri_to_vertices_and_faces_chunk_tensors`  + tests
- [x] load vertices+faces to point cloud
- [x] check and update documentation, if required. See [guide](https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md#documentation-guidelines)

2022-11-01 12:32 UTC, alaeddine-13 reviewed
we should add documentation here
https://docarray.jina.ai/datatypes/mesh/

2022-11-01 12:32 UTC, alaeddine-13 commented on docarray/document/mixins/mesh.py
> +            )
I think we should raise an error here

2022-11-01 12:34 UTC, alaeddine-13 commented on docarray/document/mixins/mesh.py
> +        ]
maybe let's enforce the schema here with `id` and later retrieve with `self.chunks['vertices']`

2022-11-01 13:11 UTC, samsja commented on docarray/document/mixins/mesh.py
> +    def load_uri_to_vertices_and_faces_chunk_tensors(self: 'T') -> 'T':
```suggestion
    def load_uri_to_vertices_and_faces(self: 'T') -> 'T':
```

name is too long IMO (even though it stick to our old naming convention)

2022-11-01 13:11 UTC, samsja commented on docarray/document/mixins/mesh.py
> +    def load_vertices_and_faces_chunk_tensors_to_point_cloud_tensor(
same lets rename here

2022-11-01 14:29 UTC, alaeddine-13 commented on docarray/document/mixins/mesh.py
> +        ]
alright makes sense then

2022-11-01 14:34 UTC, alaeddine-13 commented on docs/datatypes/mesh/index.md
> +## Mesh
the section title is `3D Mesh` above, and then we explain point cloud and go back to mesh.
It feels a bit weird to me, maybe we should name this one `Vertices and Faces representation` and the other one `point cloud representation` ?

2022-11-01 15:03 UTC, alaeddine-13 commented on docs/datatypes/mesh/index.md
> +## Mesh
yes I agree

2022-11-01 16:23 UTC, samsja approved these changes
lgtm to me as well. @JohannesMessner what do u think about the naming of the function ?

2022-11-01 16:55 UTC, JohannesMessner requested changes

2022-11-01 16:55 UTC, JohannesMessner commented on docs/datatypes/mesh/index.md
> +doc = Document(uri='viking.glb').load_uri_to_point_cloud_tensor(1000)
let's explain this `1000` (one sentence is enough), even if it is maybe clear from the context.
Also, if it has a keyword we should pass it using this keyword, for increased clarity.

2022-11-01 22:46 UTC, NicholasDunham requested changes

2022-11-01 22:46 UTC, NicholasDunham commented on docs/datatypes/mesh/index.md
> +In DocArray, you can load a mesh and save its vertices and faces to a Documents `.chunks` as follows:
```suggestion
In DocArray, you can load a mesh and save its vertices and faces to a Document's `.chunks` as follows:
```

2022-11-01 22:46 UTC, NicholasDunham commented on docs/datatypes/mesh/index.md
> +This stores the vertices and faces in `.tensor` of two separate sub-Documents in a Documents `.chunks`. Both sub-Documents have a name assigned to them ('vertices' or 'faces''), which is saved in `.t
```suggestion
This stores the vertices and faces in `.tensor` of two separate sub-Documents in a Document's `.chunks`. Each sub-Document has a name assigned to it ('vertices' or 'faces'), which is saved in `.tags`:
```

2022-11-01 22:46 UTC, NicholasDunham commented on docs/datatypes/mesh/index.md
> +Point cloud is a representation of a 3D mesh. It is made by repeated and uniformly sampling points within the 3D body. Comparing to the mesh representation, point cloud is a fixed size ndarray and he
```suggestion
A point cloud is a representation of a 3D mesh. It is made by repeatedly and uniformly sampling points within the 3D body. Compared to the mesh representation, the point cloud is a fixed size ndarray and hence easier for deep learning algorithms to handle. In DocArray, you can simply load a 3D mesh and convert it into a point cloud via:
```

2022-11-02 11:28 UTC, hanxiao approved these changes

2022-11-02 11:28 UTC, merged